# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  $puppet = <<PUPPET
    sudo dnf install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
    sudo dnf install -y puppet
PUPPET

  $modules = <<MODULES
    puppet module install puppetlabs/mysql
    puppet module install puppetlabs-firewall
	puppet module install puppetlabs-docker
    sudo cp -vR ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/
MODULES

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.box = "shekeriev/centos-8-minimal"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.provision "shell", inline: $puppet, privileged: false

  config.vm.define 'docker' do |docker|
    docker.vm.hostname = 'docker'
    docker.vm.network 'private_network', ip: '192.168.50.5'
    docker.vm.provision "shell", inline: $modules, privileged: false
	docker.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "docker.pp"
      puppet.options = "--verbose --debug"
    end
  end
end
